# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eada95a7cdd790c8494fed721872c8763fa88c95869561cb5408b23aefdb7af420c2e801c0730b08063071a0890fc89381fa3fc88fb6a7464fba0d7b4fc1ea68

test:
  secret_key_base: 23fdeb9b8039d08cb88fdaf5139cb72ee473b028cd9eda35ecc473cbc795392d66d10370345a76463ed2cd142ce93f65453d1b38a74797fda64b999452256d3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
